=== clintonmao/venus/venus-demo/venus-demo-consumer/src/main/resources/conf/venus-client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="venus-client">
    <xs:complexType>
      <xs:all>
        <xs:element ref="remotes" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="services" maxOccurs="1"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="remotes">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="remote"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="remote">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="factory">
        	
        </xs:element>
        <xs:element ref="pool"/>
        <xs:element ref="authenticator" maxOccurs="1" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="factory">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="property" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pool">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="property" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="authenticator">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="property" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="class" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="services">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="service" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="service">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="property"/>
        <xs:element minOccurs="0" ref="endpoint" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="remote" use="optional" type="xs:NCName"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="endpoint">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="soTimeout" use="optional" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== clintonmao/venus/venus-demo/venus-demo-consumer/src/test/resources/hello-venus-client.xml
<?xml version="1.0" encoding="utf-8"?>
<venus-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="venus-client.xsd">
	<remotes>
		<remote name="helloRemote" loadbalance="1">
			<!-- 与远程连接的socket相关的配置 -->
			<factory>
				<!-- 支持多节点负责均衡的高可用配置，默认采用轮询  -->
				<property name="ipAddressList">${monitor.venus.bus.ipAddressList}</property>
				<!-- socket的sendBuffer缓冲区大小，单位:Kcd acd  -->
				<property name="sendBufferSize">${venus.socket.sendBufferSize:64}</property>
				<!-- socket的receiveBuffer缓冲区大小，单位:K -->
				<property name="receiveBufferSize">${venus.socket.receiveBufferSize:64}</property>
				<property name="soTimeout">5000</property>
			</factory>
			
			<!-- 与每个远程节点的连接池配置，与apache的commons-pool配置一致 -->
			<pool>
				<property name="maxActive">10</property>
				<property name="maxIdle">30</property>
				<property name="minIdle">10</property>
				<property name="minEvictableIdleTimeMillis">60000</property>
				<property name="timeBetweenEvictionRunsMillis">60000</property>
				<property name="testOnBorrow">true</property>
				<property name="testWhileIdle">true</property>
			</pool>
			
			<!-- 采用 Dummy方式 认证 -->
			<authenticator class="com.meidusa.venus.client.authenticate.DummyAuthenticator">
				<property name="serializeType">0</property>
			</authenticator>
		</remote>
	</remotes>

	<!-- 服务接口列表 -->
	<services>
		<!-- 定义服务以及指定该服务提供方的远程相关配置 -->
		<!--
		<service type="com.saic.framework.message.UniMessageService" remote="UMSRemote"/>
		-->
		<service type="com.chexiang.venus.demo.provider.HelloService" registerUrl="injvm://localhost"/>

		<!--
		<service type="com.athena.service.api.AthenaDataService" remote="monitor-remote"/>
		-->
		<!--
		String host = "10.32.174.22";
        String host = "10.47.16.58";
        String host = "10.47.58.63";
        10.47.58.63:16800
        -->
		<service type="com.athena.service.api.AthenaDataService" ipAddressList="10.32.174.23:16800"/>
	</services>
</venus-client>
